services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    restart: unless-stopped

    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    ports:
      - "9200:9200"

    volumes:
      - es-booking-data:/usr/share/elasticsearch/data

    networks:
      - infra_booking-network

volumes:
  es-booking-data:

networks:
  infra_booking-network:
    external: true
